# -*- coding: utf-8 -*-
"""website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzrLZQ4u_QQjXPIcIza_vcMBeJJ8IxMy
"""

import requests

def check_website(url):
    try:
        response = requests.get(url, timeout=5)
        return f"Website {url} is up (Status: {response.status_code})"
    except requests.exceptions.RequestException:
        return f"Website {url} is unreachable."

print(check_website("https://uok.ac.rw"))